### ISSUE TITLE
Example using a BLOB column in a table

### ISSUE THREAD

**Issue by miked1959blue** [RonnyWeiss/APEX-Lazy-Image-Swiper#1]
Hi, I am trying to get the plug-in to work using BLOBs in a table - but struggling a little bit. Essentially I have an APEX Collection containing ID, MIME_TYPE and the BLOB. My Apex Collection is:

begin

  if apex_collection.collection_exists(p_collection_name => 'USER_IMAGES') then
    APEX_COLLECTION.DELETE_COLLECTION( p_collection_name => 'USER_IMAGES');
  end if;

  apex_collection.create_collection_from_query(p_collection_name=>'USER_IMAGES', p_query=>'select document_id as C001, document_mime_type as C002 , document as BLOB001 from t_docs where object_id = ''' || :P962_MASTER_USER_ID || ''' and document_tab_type = ''I'' and ent_object_id = (select ent_object_id from t_ent_objects where ent_object_name = ''USERS'')');

end;
                                                                                                                                          

My Lazy Image query is:

SELECT
    /* Source type - 'blob' when load from  table and 'url when SRC_VALUE is a link */
    
    'blob' AS SRC_TYPE,
    
    /* Primary Key when use load from binary table e.g. idend or file name (Is used in Attributes in (Execute to get Image Sources) or url to image when SRC_TYPE 'url' */
    
    --'https://github.com/RonnyWeiss/Apex-Advent-Calendar/raw/master/img/full/0' || ROWNUM || '.jpg' AS SRC_VALUE,
    
    b.C001 as src_value,
    
    /* Title of the image */
    
    'Image Title ' || ROWNUM AS SRC_TITLE,
    
    /* type of the action - can be like( event "like" if fired onto region when DA should be fired and "ACTION" can also fire JS), link, linkopentab, javascript (Executed by eval() ) */
    
    DECODE(ROWNUM, 1 , 'like' , 3 ,'link' , 'linkopentab') AS ACTION_TYPE,
    
    /* executed action */
    
    DECODE( ROWNUM , 1 ,'apex.message.showPageSuccess( "Thank your for liking my image!" );' , 'https://github.com/RonnyWeiss') AS ACTION
    
from T_DOCS a, apex_collections b 
where a.document_id     = b.c001 
  and collection_name   = 'USER_IMAGES'
  and object_id         = :P962_MASTER_USER_ID
  and document_tab_type = 'I'
  and ent_object_id     = (select ent_object_id from t_ent_objects where ent_object_name = 'USERS')

But I cant seem to get the image to display. In the above SQL I also change b.C001 to be b.BLOB001 but that did not work either. 

Are to able to advise - I think your plug-in is excellent and exactly what I am looking for.

Yours,

Mike Davidson

**Comment by ger88** [comment]
Hallo Ronny,
ich habe leider genau das gleiche Problem.
Execute to get Image Sources:
DECLARE
    VR_FILE_NAME     VARCHAR2(200);
    VR_MIME_TYPE     VARCHAR2(200);
    VR_BINARY_FILE   BLOB;
BEGIN
    SELECT file_name
          ,mime_type
          ,blob_data
      INTO
        VR_FILE_NAME,
        VR_MIME_TYPE,
        VR_BINARY_FILE
   FROM sale_t_document doc,
       sale_t_document_type typ
 WHERE doct_oid = typ.oid
   AND typ.oid = 100
   AND bimpt_oid = :P706_OID;

    :FILE_NAME     := VR_FILE_NAME;
    :MIME_TYPE     := VR_MIME_TYPE;
    :BINARY_FILE   := VR_BINARY_FILE;
EXCEPTION
    WHEN OTHERS THEN
        APEX_DEBUG.ERROR(SQLERRM);
        APEX_DEBUG.ERROR(DBMS_UTILITY.FORMAT_ERROR_STACK);
END;   

Aber wie muss ich das Select ändern?
SELECT
    'blob' AS SRC_TYPE,
    'https://github.com/RonnyWeiss/Apex-Advent-Calendar/raw/master/img/full/0' ||
    ROWNUM || '.jpg' AS SRC_VALUE,
    'Image Title ' || ROWNUM AS SRC_TITLE,
    DECODE(ROWNUM,1,'like',3,'link','linkopentab') AS ACTION_TYPE,
    DECODE(ROWNUM,1,'apex.message.showPageSuccess( "Thank your for liking my image!" );','https://github.com/RonnyWeiss') AS ACTION
FROM
    DUAL
CONNECT BY
    ROWNUM <= 9

Bitte um Hilfe, Danke Gerhard

**Comment by malekammous** [comment]
same problem here.

**Comment by malekammous** [comment]
same problem here.

**Comment by ger88** [comment]
Hi,
I have solved the problem :-)

Create a Dynamic Action, when Page load:

BEGIN
  IF APEX_COLLECTION.COLLECTION_EXISTS(p_collection_name => 'IMG_COLLECTION') THEN
    APEX_COLLECTION.DELETE_COLLECTION( p_collection_name => 'IMG_COLLECTION');
  END IF;
  --
  APEX_COLLECTION.CREATE_COLLECTION('IMG_COLLECTION');
  --
  FOR ins IN (SELECT doc.oid, mime_type, blob_data
                FROM sale_t_document
               WHERE bimpt_oid = :P706_OID) LOOP
    --
    APEX_COLLECTION.ADD_MEMBER(
      p_collection_name => 'IMG_COLLECTION',
      p_c001            => ins.oid,
      p_c002            => ins.mime_type,
      p_blob001         => ins.blob_data
    );
  END LOOP;
END;

Execute to get Image Sources:

DECLARE
  vr_file_name     VARCHAR2(200);
  vr_mime_type     VARCHAR2(200);
  vr_binary_file   BLOB;
  vr_pk            VARCHAR2(200) := :PK;
  vr_col_name      VARCHAR2(200) := 'IMG_COLLECTION';
BEGIN
  SELECT C001,
         C002,
         BLOB001
    INTO vr_file_name,
         vr_mime_type,
         vr_binary_file
    FROM apex_collections
   WHERE collection_name = vr_col_name
     AND c001 = :PK
     AND rownum = 1;
  --
  :FILE_NAME     := vr_file_name;
  :MIME_TYPE     := vr_mime_type;
  :BINARY_FILE   := vr_binary_file;
  --
EXCEPTION WHEN OTHERS THEN
  APEX_DEBUG.ERROR(SQLERRM);
  APEX_DEBUG.ERROR(DBMS_UTILITY.FORMAT_ERROR_STACK);
END;

Select for Region:

SELECT 'blob' AS SRC_TYPE,
       oid AS SRC_VALUE,
       file_name AS SRC_TITLE,
       null AS ACTION_TYPE,
       null AS ACTION
  FROM sale_t_document
 WHERE bimpt_oid = :P706_OID
 ORDER BY oid

Lg,
Gerhard

**Comment by ashdease** [comment]
Hi I am trying to implement this plugin, I am using the code Gerhard has provided above using collections, 

I am getting a compile error on the following line of code for some reason. I am using APEX 19.1, can you help I have attached screenshot of compile error too.

ORA-06550: line 21, column 19: PLS-00382: expression is of wrong type
**:BINARY_FILE := vr_binary_file;**

My region query is as follows
SELECT 'file_blob' AS SRC_TYPE,
              id AS SRC_VALUE,
              filename AS SRC_TITLE,
             null AS ACTION_TYPE,
            null AS ACTION
FROM Test
WHERE T_ID = 1301456005761
ORDER BY id

Please can someone help.

Regards
Ash

![Compile Error](https://user-images.githubusercontent.com/38276598/71667260-3d7c0300-2d5c-11ea-85aa-7e828dee92d3.png)

![Image slider error](https://user-images.githubusercontent.com/38276598/71667446-078b4e80-2d5d-11ea-8467-b0b579d1137a.png)
