### ISSUE TITLE
how show blob from table?

### ISSUE THREAD

**Issue by rastin167** [RonnyWeiss/APEX-Lazy-Image-Swiper#2]
hi,
i use table with blob column for image.
how show blob from table this plugin?
my query is :

SELECT
     'blob' AS SRC_TYPE,
     '<img src="'||APEX_UTIL.GET_BLOB_FILE_SRC('P21_PIC',p.ID)||'" height="100" width="100" />'  AS SRC_VALUE,
   -- dbms_lob.getlength(p.PIC)  AS SRC_VALUE,
    p.PRODUCT_NAME AS SRC_TITLE,
    DECODE(ROWNUM,1,'like',3,'link','linkopentab') AS ACTION_TYPE,
    DECODE(ROWNUM,1,'apex.message.showPageSuccess( "Thank your for liking my Product!" );','http://') AS ACTION
FROM
    PRODUCTS p

but not show image , why?

**Comment by RonnyWeiss** [comment]
Please load update an check the comments and help again in the plug-in hope it works, else please open issue again
